# Generated by Django 5.1.3 on 2024-11-15 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agentLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(upload_to='imgs/')),
                ('age', models.IntegerField(max_length=50)),
                ('positions', models.CharField(choices=[('NS', 'Network Security'), ('AS', 'Application Security'), ('IS', 'Incident Response'), ('IAM', 'Identity and Access Management'), ('CR', 'Cryptography'), ('CG', 'Compliance and Governance'), ('TI', 'Threat Intelligence')], max_length=30)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
