# Generated by Django 5.1.3 on 2024-11-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlists',
            name='age',
            field=models.IntegerField(),
        ),
    ]
